### ISSUE TITLE
Only one instance receive a message

### ISSUE THREAD

**Issue by litvinovvo** [thinkalpha/socket.io-amqp0#6]
Hi, trying to use your adapter and unfortunately run into strange behaviour, on io.emit() only one random instance getting the message

Here minimal repo for reproduce: https://github.com/litvinovvo/socket.io-amqp0-reproduce

On the other side the same code but with redis adapter working fine.

Thanks in advance, maybe it is some missconfiguration from my side

**Comment by bytenik** [comment]
If you're running multiple instances on the same host for testing, you'd have to set the `instanceName` option. It defaults to the system hostname, and so it sounds like your multiple instances are competing over the same queue (one exchange -> one single queue) instead of doing fanout (one exchange to a queue per instance).

**Comment by litvinovvo** [comment]
With a uniq instanceName it is working just as expected, thank you!
